"""modify ticket table

Revision ID: ebe4f633b463
Revises: 5d6dbe8429f2
Create Date: 2026-09-15 23:50:50.303255

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ebe4f633b463"
down_revision: str | Sequence[str] | None = "5d6dbe8429f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE ticket SET status = 'reported' WHERE status IS NULL")
    op.execute("ALTER TABLE ticket ALTER COLUMN status SET DEFAULT 'reported'")
    op.execute("ALTER TABLE ticket ALTER COLUMN status SET NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE ticket ALTER COLUMN status DROP NOT NULL")
    op.execute("ALTER TABLE ticket ALTER COLUMN status DROP DEFAULT")
    # ### end Alembic commands ###
